import * as ort from "onnxruntime-node";
const path = process.argv[2];
let t = Date.now();
const session = await ort.InferenceSession.create(path, { graphOptimizationLevel: "basic", enableCpuMemArena: false, enableMemPattern: false, executionMode: "sequential", intraOpNumThreads: 2 });
const meta = session.inputMetadata?.[0]?.shape ?? [1,3,1024,1024];
const [n,c,h,w] = meta.map((d) => typeof d === "number" ? d : 1024);
console.log("load ms", Date.now() - t, session.inputNames, session.outputNames, [n,c,h,w]);
const data = new Float32Array(n * c * h * w).fill(0.1);
t = Date.now();
const out = await session.run({ [session.inputNames[0]]: new ort.Tensor("float32", data, [n, c, h, w]) });
console.log("infer ms", Date.now() - t, "out", out[session.outputNames[0]].dims, "rss MB", Math.round(process.memoryUsage().rss / 1e6));
