export const ENV = {
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  /** Verified Google email that is granted the admin role on sign-in. */
  ownerEmail: (process.env.OWNER_EMAIL ?? "").trim().toLowerCase(),
  isProduction: process.env.NODE_ENV === "production",
  openRouterApiKey: process.env.OPENROUTER_API_KEY ?? "",
  openRouterBaseUrl: (process.env.OPENROUTER_BASE_URL ?? "https://openrouter.ai/api/v1").replace(/\/+$/, ""),
  openRouterLlmModel: process.env.OPENROUTER_LLM_MODEL ?? "",
  openRouterImageModel: process.env.OPENROUTER_IMAGE_MODEL ?? "google/gemini-2.5-flash-image",
  openRouterImageFallbackModel: process.env.OPENROUTER_IMAGE_FALLBACK_MODEL ?? "openai/gpt-5-image",
  s3Endpoint: process.env.S3_ENDPOINT ?? "",
  s3Region: process.env.S3_REGION ?? "auto",
  s3Bucket: process.env.S3_BUCKET ?? "",
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
  stripeSecretKey: process.env.IWANTPHOTO_STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.IWANTPHOTO_STRIPE_WEBHOOK_SECRET ?? "",
  stripeBillingEnabled: process.env.IWANTPHOTO_BILLING_ENABLED === "true",
  appBaseUrl: process.env.APP_BASE_URL ?? "https://iwantphoto.com",
  stripeProPriceId: process.env.STRIPE_PRO_PRICE_ID ?? "price_1UGffkIrIlUINMyl5nDxSnjh",
  stripeBusinessPriceId: process.env.STRIPE_BUSINESS_PRICE_ID ?? "price_1UGffmIrIlUINMylflXVCT9i",
  stripeCreditFlex25PriceId: process.env.IWANTPHOTO_STRIPE_CREDIT_FLEX_25_PRICE_ID ?? "price_1UGgTgIrIlUINMylqdFNLMK6",
  stripeCreditValue100PriceId: process.env.IWANTPHOTO_STRIPE_CREDIT_VALUE_100_PRICE_ID ?? "price_1UGgTiIrIlUINMylY6bezPU5",
  stripeCreditStudio250PriceId: process.env.IWANTPHOTO_STRIPE_CREDIT_STUDIO_250_PRICE_ID ?? "price_1UGgTlIrIlUINMylJU4w7A3p",
  resendApiKey: process.env.IWANTPHOTO_RESEND_API_KEY ?? "",
  resendFromEmail: process.env.IWANTPHOTO_RESEND_FROM_EMAIL ?? "Iwantphoto <alerts@iwantphoto.com>",
};
