export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  stripeSecretKey: process.env.IWANTPHOTO_STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.IWANTPHOTO_STRIPE_WEBHOOK_SECRET ?? "",
  stripeBillingEnabled: process.env.IWANTPHOTO_BILLING_ENABLED === "true",
  appBaseUrl: process.env.APP_BASE_URL ?? "https://iwantphoto.com",
  stripeProPriceId: process.env.STRIPE_PRO_PRICE_ID ?? "price_1UGffkIrIlUINMyl5nDxSnjh",
  stripeBusinessPriceId: process.env.STRIPE_BUSINESS_PRICE_ID ?? "price_1UGffmIrIlUINMylflXVCT9i",
  stripeCreditFlex25PriceId: process.env.IWANTPHOTO_STRIPE_CREDIT_FLEX_25_PRICE_ID ?? "price_1UGgTgIrIlUINMylqdFNLMK6",
  stripeCreditValue100PriceId: process.env.IWANTPHOTO_STRIPE_CREDIT_VALUE_100_PRICE_ID ?? "price_1UGgTiIrIlUINMylY6bezPU5",
  stripeCreditStudio250PriceId: process.env.IWANTPHOTO_STRIPE_CREDIT_STUDIO_250_PRICE_ID ?? "price_1UGgTlIrIlUINMylJU4w7A3p",
  resendApiKey: process.env.IWANTPHOTO_RESEND_API_KEY ?? "",
  resendFromEmail: process.env.IWANTPHOTO_RESEND_FROM_EMAIL ?? "Iwantphoto <alerts@iwantphoto.com>",
};
